// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1OObrhnMnZher2vZF_cXaYl3ugUxqcA',
    appId: '1:832097821716:web:53e4bcd77c4d8fd2073301',
    messagingSenderId: '832097821716',
    projectId: 'citychannel-bb5b5',
    authDomain: 'citychannel-bb5b5.firebaseapp.com',
    storageBucket: 'citychannel-bb5b5.appspot.com',
    measurementId: 'G-6LWSKQ94WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTHZWLVT8qMKhr4fH24CwVzDWM2qSwxMM',
    appId: '1:832097821716:android:06bbe09d989887fb073301',
    messagingSenderId: '832097821716',
    projectId: 'citychannel-bb5b5',
    storageBucket: 'citychannel-bb5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIjuUfA6EpgaMtPj1tDzhcYJeQF3uPR5A',
    appId: '1:832097821716:ios:ba005dbf518c6fc9073301',
    messagingSenderId: '832097821716',
    projectId: 'citychannel-bb5b5',
    storageBucket: 'citychannel-bb5b5.appspot.com',
    iosBundleId: 'com.example.citychannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIjuUfA6EpgaMtPj1tDzhcYJeQF3uPR5A',
    appId: '1:832097821716:ios:dfa079ff78b2fa56073301',
    messagingSenderId: '832097821716',
    projectId: 'citychannel-bb5b5',
    storageBucket: 'citychannel-bb5b5.appspot.com',
    iosBundleId: 'com.example.citychannel.RunnerTests',
  );
}
